### PR TITLE
index_record: pass index in before_record_index sig

### PR DESCRIPTION
**Pull request by tomaszgy**
Signed-off-by: Tomasz tomaszgy@gmail.com

### CODE REVIEW

**Comment by kaplun** [comment]
Can you increase the version? Is the commit log title within 50 chars? :)

**Comment by kaplun** [comment]
@tomaszgy can you increase the version in version.py? So that then we force its installation in inspire-next.

---

Ups! Closed by mistake :)

**Comment by tomaszgy** [comment]
Version added.

**Comment by kaplun** [comment]
Aagh! I merged without checking the version :stuck_out_tongue: It is formatted YYYYDDMM rather than YYYYMMDD

**Comment by tomaszgy** [comment]
I thought it's a pattern as the previous version was formatted in the same style. Anyway, next version will be correct :smile:.

**Comment by kaplun** [comment]
Yep I corrected it already :dancer: Nope. It was a :bug:

**Comment by tomaszgy** [comment]
Thanks!

**Pull request merged**
