### PR TITLE
record: save deep copy of initial json

### PR DESCRIPTION
**Pull request by tomaszgy**
- deep copy can be used after update to compare new version of the record with the old one

Signed-off-by: Tomasz tomaszgy@gmail.com

### CODE REVIEW

**Comment by jmartinm** [comment]
After reading https://github.com/inveniosoftware/invenio-records/issues/87#issuecomment-162644075

And seeing the dependencies of `invenio-records` - https://github.com/inveniosoftware/invenio-records/blob/master/setup.py#L81-L88 (which don't include any other invenio packages)

I am wondering if it would be feasible to start using the new invenio-records as the API (https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/api.py) seems to not have changed much.

**Comment by kaplun** [comment]
There are hidden changes in the model and hidden dependencies on overhauled `invenio-pidstore`. So definitively is going to be great to upgrade, but after we have :shipit: the search milestone.

**Comment by kaplun** [comment]
@tomaszgy can you add to the same PR the enhanced signal?

**Comment by kaplun** [comment]
> deep copy can be used after update to compare new version of the record with the old one

Please, amend the commit log to follow the typical: "\* Introduces bla bla bla." and terminate wotj a dot, and go new line after 70 char.

**Comment by jalavik** [comment]
Sorry as I may not be fully informed on the context, but is this mostly for convenience that it is added to the `Record` object and not just kept in a variable in the client code?

**Comment by lnielsen** [comment]
@jmartinm Invenio-Records 1.0.0 is quite a big change. 1) It uses UUIDs for identifying records 2) If you want record display you need Invenio-PIDStore + Invenio-Records-UI:

http://pythonhosted.org/invenio-records-ui/
http://pythonhosted.org/invenio-pidstore/

**Comment by tomaszgy** [comment]
(I am @kaplun replying from @tomaszgy keyboard :smile: )

> Sorry as I may not be fully informed on the context, but is this mostly for convenience that it is added to the Record object and not just kept in a variable in the client code?

The client code here, would be a receiver which is subscribed to the signal `after_record_update`, so in the current implementation, the only way for the receiver to know the previous version of a record being modified is to query it from the record object being sent there.

**Comment by tomaszgy** [comment]
@kaplun: changes applied

**Comment by kaplun** [comment]
Merged. Can you create a corresponding PR for inspirehep repo to use this new hash?

**Comment by tomaszgy** [comment]
PR opened in https://github.com/inspirehep/inspire-next/pull/624.

**Pull request merged**
